# Generated by Django 5.1.5 on 2025-02-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_role_id_user_roles_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=20),
        ),
    ]
