# Generated by Django 5.1.5 on 2025-02-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_seller_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
    ]
