# Generated by Django 5.1.5 on 2025-02-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_remove_seller_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_name',
        ),
    ]
