# Generated by Django 5.1.5 on 2025-02-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_remove_seller_email_remove_seller_seller_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='user_no',
            new_name='user',
        ),
    ]
