# Generated by Django 5.1.5 on 2025-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_user_no_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
