# Generated by Django 5.1.5 on 2025-02-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(),
        ),
    ]
