# Generated by Django 5.1.5 on 2025-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
