# Generated by Django 5.1.5 on 2025-02-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
