# Generated by Django 5.1.5 on 2025-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
