services:
  - type: web
    name: ecomm-neomart
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Demo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neomart
          property: connectionString
      - key: SECRET_KEY
        value: Mathan2306
      - key: ALLOWED_HOSTS
        value: ecomm-neomart.onrender.com
